library(tidyr)
library(dplyr)
lowerletters <- tolower(refine_original$company)
refiner <- mutate(refine_original, company = substr(lowerletters,1,stop = 1))
refiner$company <- gsub("^[p|f]", "philips", refiner$company)
refiner$company <- gsub("^[a]", "akzo", refiner$company)
refiner$company <- gsub("^[v]", "van houten", refiner$company)
refiner$company <- gsub("^[u]", "unilever", refiner$company)
refiner <- separate(refiner, Product.code...number, c("product_code", "product_number"), sep = "-")
refiner <- mutate(refiner, "product_category" = product_code)
refiner$product_category <- gsub("^[p]", "Smartphone", refiner$product_category)
refiner$product_category <- gsub("^[v]", "TV", refiner$product_category)
refiner$product_category <- gsub("^[x]", "Laptop", refiner$product_category)
refiner$product_category <- gsub("^[q]", "Tablet", refiner$product_category)
refiner <- unite(refiner, "full_address", address : country, sep = "," )
refiner <- mutate(refiner, company_philips = ifelse(company == "philips", 1, 0))
refiner <- mutate(refiner, company_akzo = ifelse(company == "akzo", 1, 0))
refiner <- mutate(refiner, company_unilever = ifelse(company == "unilever", 1, 0))
refiner <- mutate(refiner, company_van_houten = ifelse(company == "van houten", 1, 0))
refiner <- mutate(refiner, product_smartphone = ifelse(product_category == "Smartphone", 1, 0))
refiner <- mutate(refiner, product_laptop = ifelse(product_category == "Laptop", 1, 0))
refiner <- mutate(refiner, product_tv = ifelse(product_category == "TV", 1, 0))
refiner <- mutate(refiner, product_tablet = ifelse(product_category == "Tablet", 1, 0))
refine_clean <- refiner
write.csv(refine_clean, file = "refine_clean.csv")

